export const LANGUAGES = [
    ["markdown", "Markdown", ".md"],
    ["html", "HTML", ".html"],
    ["css", "CSS", ".css"],
    ["javascript", "JavaScript", ".js"],
    ["bash", "Bash", ".sh"],
    ["c", "C", ".c"],
    ["cpp", "C++", ".cpp"],
    ["cs", "C#", ".cs"],
    ["erlang", "Erlang", ".erl"],
    ["go", "Go", ".go"],
    ["haskell", "Haskell", ".hs"],
    ["rust", "Rust", ".rs"],
    ["java", "Java", ".java"],
    ["json", "JSON", ".json"],
    ["kotlin", "Kotlin", ".kt"],
    ["latex", "LaTeX", ".tex"],
    ["php", "PHP", ".php"],
    ["python", "Python", ".py"],
    ["scala", "Scala", ".scala"],
    ["sql", "SQL", ".sql"],
    ["toml", "TOML", ".toml"],
    ["typescript", "TypeScript", ".ts"],
];
