[server]
bind_addr = "localhost:6000"
host_addr = "localhost:6000"

[security]
secret_key = "magic"
max_post_size = 262144 # 256 KiB
max_expiration_seconds = 2592123 # 30 days

[redis]
url = "redis://localhost:6379"
key_prefix = "pastebin"
max_open_connections = 32
