[server]
bind_addr = "localhost:8000"
host_addr = "localhost"

[security]
secret_key = "magic"
max_body_length = 262144 # 256 KiB
max_expiration_seconds = 2592123 # 30 days
max_qps = 1000

[redis]
url = "redis://localhost:6379"
key_prefix = "pastebin"
max_open_connections = 32
